paths:
  pretrained_prior_path: kandinsky-community/kandinsky-2-2-prior
  pretrained_image_encoder: kandinsky-community/kandinsky-2-2-prior
  scheduler_path: kandinsky-community/kandinsky-2-2-prior
  image_processor_path: kandinsky-community/kandinsky-2-2-prior
  text_encoder_path: kandinsky-community/kandinsky-2-2-prior
  tokenizer_path: kandinsky-community/kandinsky-2-2-prior

dataset:
  train_images_paths_csv: train/dataset.csv
  val_images_paths_csv:

training:
  train_batch_size: 1
  val_batch_size: 1
  lr: 1e-05
  weight_decay: 0.0
  num_epochs: 0
  output_dir: train/lora
  lr_scheduler: constant
  max_train_steps: 500
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  lr_warmup_steps: 0
  snr_gamma:
  use_8bit_adam: false
  resume_from_checkpoint:
  allow_tf32: false
  dataloader_num_workers: 0
  logging_dir: logs
  mixed_precision: fp16
  report_to: tensorboard
  local_rank: -1
  checkpointing_steps: 500
  checkpoints_total_limit:
  rank: 4
  seed:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0

prior:
  use_ema: false
  output_name: lora_prior
